/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author Edho
 */
public class InputNilai extends javax.swing.JFrame {
    
    boolean simpleinput, ips;
    public static ImageIcon complex, simple;
    /**
     * Creates new form InputNilai
     */
    public InputNilai() {
        this.complex = new javax.swing.ImageIcon(getClass().getResource("/Icons/list30x30.png"));
        this.simple = new javax.swing.ImageIcon(getClass().getResource("/Icons/bullets30x30.png"));
        this.simpleinput = false;
        this.ips = false;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMenuName = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnJurusanMIPA = new javax.swing.JButton();
        btnJurusanIPS = new javax.swing.JButton();
        pnlJurusan = new javax.swing.JPanel();
        lblBIndo = new javax.swing.JLabel();
        lblBIng = new javax.swing.JLabel();
        lblMTK = new javax.swing.JLabel();
        lblMinat1 = new javax.swing.JLabel();
        lblMinat2 = new javax.swing.JLabel();
        lblMinat3 = new javax.swing.JLabel();
        pnlInputNilai = new javax.swing.JPanel();
        pnlInputNormal = new javax.swing.JPanel();
        lblSemester = new javax.swing.JLabel();
        lblSmt1 = new javax.swing.JLabel();
        lblSmt2 = new javax.swing.JLabel();
        lblSmt3 = new javax.swing.JLabel();
        lblSmt4 = new javax.swing.JLabel();
        lblSmt5 = new javax.swing.JLabel();
        txtBindo1 = new javax.swing.JTextField();
        txtBindo2 = new javax.swing.JTextField();
        txtBindo3 = new javax.swing.JTextField();
        txtBindo4 = new javax.swing.JTextField();
        txtBindo5 = new javax.swing.JTextField();
        txtBing1 = new javax.swing.JTextField();
        txtBing2 = new javax.swing.JTextField();
        txtBing3 = new javax.swing.JTextField();
        txtBing4 = new javax.swing.JTextField();
        txtBing5 = new javax.swing.JTextField();
        txtMTK1 = new javax.swing.JTextField();
        txtMTK2 = new javax.swing.JTextField();
        txtMTK3 = new javax.swing.JTextField();
        txtMTK4 = new javax.swing.JTextField();
        txtMTK5 = new javax.swing.JTextField();
        txtMinat11 = new javax.swing.JTextField();
        txtMinat12 = new javax.swing.JTextField();
        txtMinat13 = new javax.swing.JTextField();
        txtMinat14 = new javax.swing.JTextField();
        txtMinat15 = new javax.swing.JTextField();
        txtMinat21 = new javax.swing.JTextField();
        txtMinat22 = new javax.swing.JTextField();
        txtMinat23 = new javax.swing.JTextField();
        txtMinat24 = new javax.swing.JTextField();
        txtMinat25 = new javax.swing.JTextField();
        txtMinat31 = new javax.swing.JTextField();
        txtMinat32 = new javax.swing.JTextField();
        txtMinat33 = new javax.swing.JTextField();
        txtMinat34 = new javax.swing.JTextField();
        txtMinat35 = new javax.swing.JTextField();
        pnlInputSimple = new javax.swing.JPanel();
        txtInputRataBindo = new javax.swing.JTextField();
        txtInputRataBing = new javax.swing.JTextField();
        txtInputRataMTK = new javax.swing.JTextField();
        txtInputRataMinat1 = new javax.swing.JTextField();
        txtInputRataMinat2 = new javax.swing.JTextField();
        txtInputRataMinat3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        btnUbahInput = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlTitle.setBackground(new java.awt.Color(12, 142, 148));

        lblTitle.setFont(new java.awt.Font("GOGOIA", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("PREDICTATOR");

        lblMenuName.setFont(new java.awt.Font("Akrobat SemiBold", 0, 36)); // NOI18N
        lblMenuName.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuName.setText("INPUT NILAI");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuName)
                .addGap(29, 29, 29))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(lblMenuName))
                .addContainerGap())
        );

        pnlBody.setBackground(new java.awt.Color(17, 157, 164));

        lblNama.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Halo,");

        lblInfo.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Pertama-tama, masukkan nilai raport SMA mu dahulu yuk!");

        btnJurusanMIPA.setBackground(new java.awt.Color(17, 157, 164));
        btnJurusanMIPA.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        btnJurusanMIPA.setForeground(new java.awt.Color(255, 255, 255));
        btnJurusanMIPA.setText("MIPA");
        btnJurusanMIPA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btnJurusanMIPA.setContentAreaFilled(false);
        btnJurusanMIPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJurusanMIPA.setOpaque(true);
        btnJurusanMIPA.setRolloverEnabled(false);
        btnJurusanMIPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJurusanMIPAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJurusanMIPAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJurusanMIPAMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnJurusanMIPAMouseReleased(evt);
            }
        });
        btnJurusanMIPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurusanMIPAActionPerformed(evt);
            }
        });

        btnJurusanIPS.setBackground(new java.awt.Color(17, 157, 164));
        btnJurusanIPS.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        btnJurusanIPS.setForeground(new java.awt.Color(255, 255, 255));
        btnJurusanIPS.setText("IPS");
        btnJurusanIPS.setContentAreaFilled(false);
        btnJurusanIPS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJurusanIPS.setOpaque(true);
        btnJurusanIPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJurusanIPSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJurusanIPSMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJurusanIPSMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnJurusanIPSMouseReleased(evt);
            }
        });
        btnJurusanIPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurusanIPSActionPerformed(evt);
            }
        });

        pnlJurusan.setBackground(new java.awt.Color(17, 157, 164));
        pnlJurusan.setPreferredSize(new java.awt.Dimension(200, 336));

        lblBIndo.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblBIndo.setForeground(new java.awt.Color(255, 255, 255));
        lblBIndo.setText("Bahasa Indonesia");

        lblBIng.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblBIng.setForeground(new java.awt.Color(255, 255, 255));
        lblBIng.setText("Bahasa Inggris");

        lblMTK.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblMTK.setForeground(new java.awt.Color(255, 255, 255));
        lblMTK.setText("Matematika");

        lblMinat1.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblMinat1.setForeground(new java.awt.Color(255, 255, 255));
        lblMinat1.setText("Fisika");

        lblMinat2.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblMinat2.setForeground(new java.awt.Color(255, 255, 255));
        lblMinat2.setText("Kimia");

        lblMinat3.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblMinat3.setForeground(new java.awt.Color(255, 255, 255));
        lblMinat3.setText("Biologi");

        pnlInputNilai.setBackground(new java.awt.Color(17, 157, 164));
        pnlInputNilai.setForeground(new java.awt.Color(255, 255, 255));
        pnlInputNilai.setLayout(new java.awt.CardLayout());

        pnlInputNormal.setBackground(new java.awt.Color(17, 157, 164));
        pnlInputNormal.setForeground(new java.awt.Color(255, 255, 255));

        lblSemester.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(255, 255, 255));
        lblSemester.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemester.setText("SEMESTER");

        lblSmt1.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSmt1.setForeground(new java.awt.Color(255, 255, 255));
        lblSmt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmt1.setText("1");

        lblSmt2.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSmt2.setForeground(new java.awt.Color(255, 255, 255));
        lblSmt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmt2.setText("2");

        lblSmt3.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSmt3.setForeground(new java.awt.Color(255, 255, 255));
        lblSmt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmt3.setText("3");

        lblSmt4.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSmt4.setForeground(new java.awt.Color(255, 255, 255));
        lblSmt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmt4.setText("4");

        lblSmt5.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        lblSmt5.setForeground(new java.awt.Color(255, 255, 255));
        lblSmt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmt5.setText("5");

        txtBindo1.setBackground(new java.awt.Color(17, 157, 164));
        txtBindo1.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBindo1.setForeground(new java.awt.Color(255, 255, 255));
        txtBindo1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBindo1.setText("0");
        txtBindo1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBindo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBindo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindo1FocusLost(evt);
            }
        });

        txtBindo2.setBackground(new java.awt.Color(17, 157, 164));
        txtBindo2.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBindo2.setForeground(new java.awt.Color(255, 255, 255));
        txtBindo2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBindo2.setText("0");
        txtBindo2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBindo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBindo2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindo2FocusLost(evt);
            }
        });

        txtBindo3.setBackground(new java.awt.Color(17, 157, 164));
        txtBindo3.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBindo3.setForeground(new java.awt.Color(255, 255, 255));
        txtBindo3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBindo3.setText("0");
        txtBindo3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBindo3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBindo3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindo3FocusLost(evt);
            }
        });

        txtBindo4.setBackground(new java.awt.Color(17, 157, 164));
        txtBindo4.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBindo4.setForeground(new java.awt.Color(255, 255, 255));
        txtBindo4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBindo4.setText("0");
        txtBindo4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBindo4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBindo4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindo4FocusLost(evt);
            }
        });

        txtBindo5.setBackground(new java.awt.Color(17, 157, 164));
        txtBindo5.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBindo5.setForeground(new java.awt.Color(255, 255, 255));
        txtBindo5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBindo5.setText("0");
        txtBindo5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBindo5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBindo5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindo5FocusLost(evt);
            }
        });

        txtBing1.setBackground(new java.awt.Color(17, 157, 164));
        txtBing1.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBing1.setForeground(new java.awt.Color(255, 255, 255));
        txtBing1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBing1.setText("0");
        txtBing1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBing1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBing1FocusLost(evt);
            }
        });

        txtBing2.setBackground(new java.awt.Color(17, 157, 164));
        txtBing2.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBing2.setForeground(new java.awt.Color(255, 255, 255));
        txtBing2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBing2.setText("0");
        txtBing2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBing2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBing2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBing2FocusLost(evt);
            }
        });

        txtBing3.setBackground(new java.awt.Color(17, 157, 164));
        txtBing3.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBing3.setForeground(new java.awt.Color(255, 255, 255));
        txtBing3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBing3.setText("0");
        txtBing3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBing3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBing3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBing3FocusLost(evt);
            }
        });

        txtBing4.setBackground(new java.awt.Color(17, 157, 164));
        txtBing4.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBing4.setForeground(new java.awt.Color(255, 255, 255));
        txtBing4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBing4.setText("0");
        txtBing4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBing4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBing4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBing4FocusLost(evt);
            }
        });

        txtBing5.setBackground(new java.awt.Color(17, 157, 164));
        txtBing5.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtBing5.setForeground(new java.awt.Color(255, 255, 255));
        txtBing5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBing5.setText("0");
        txtBing5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBing5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBing5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBing5FocusLost(evt);
            }
        });

        txtMTK1.setBackground(new java.awt.Color(17, 157, 164));
        txtMTK1.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMTK1.setForeground(new java.awt.Color(255, 255, 255));
        txtMTK1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMTK1.setText("0");
        txtMTK1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMTK1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMTK1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMTK1FocusLost(evt);
            }
        });

        txtMTK2.setBackground(new java.awt.Color(17, 157, 164));
        txtMTK2.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMTK2.setForeground(new java.awt.Color(255, 255, 255));
        txtMTK2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMTK2.setText("0");
        txtMTK2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMTK2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMTK2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMTK2FocusLost(evt);
            }
        });

        txtMTK3.setBackground(new java.awt.Color(17, 157, 164));
        txtMTK3.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMTK3.setForeground(new java.awt.Color(255, 255, 255));
        txtMTK3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMTK3.setText("0");
        txtMTK3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMTK3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMTK3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMTK3FocusLost(evt);
            }
        });

        txtMTK4.setBackground(new java.awt.Color(17, 157, 164));
        txtMTK4.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMTK4.setForeground(new java.awt.Color(255, 255, 255));
        txtMTK4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMTK4.setText("0");
        txtMTK4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMTK4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMTK4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMTK4FocusLost(evt);
            }
        });

        txtMTK5.setBackground(new java.awt.Color(17, 157, 164));
        txtMTK5.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMTK5.setForeground(new java.awt.Color(255, 255, 255));
        txtMTK5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMTK5.setText("0");
        txtMTK5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMTK5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMTK5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMTK5FocusLost(evt);
            }
        });

        txtMinat11.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat11.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat11.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat11.setText("0");
        txtMinat11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat11FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat11FocusLost(evt);
            }
        });

        txtMinat12.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat12.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat12.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat12.setText("0");
        txtMinat12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat12FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat12FocusLost(evt);
            }
        });

        txtMinat13.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat13.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat13.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat13.setText("0");
        txtMinat13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat13FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat13FocusLost(evt);
            }
        });

        txtMinat14.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat14.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat14.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat14.setText("0");
        txtMinat14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat14FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat14FocusLost(evt);
            }
        });

        txtMinat15.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat15.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat15.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat15.setText("0");
        txtMinat15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat15FocusLost(evt);
            }
        });

        txtMinat21.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat21.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat21.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat21.setText("0");
        txtMinat21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat21FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat21FocusLost(evt);
            }
        });

        txtMinat22.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat22.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat22.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat22.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat22.setText("0");
        txtMinat22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat22FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat22FocusLost(evt);
            }
        });

        txtMinat23.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat23.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat23.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat23.setText("0");
        txtMinat23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat23FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat23FocusLost(evt);
            }
        });

        txtMinat24.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat24.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat24.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat24.setText("0");
        txtMinat24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat24FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat24FocusLost(evt);
            }
        });

        txtMinat25.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat25.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat25.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat25.setText("0");
        txtMinat25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat25.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat25FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat25FocusLost(evt);
            }
        });

        txtMinat31.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat31.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat31.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat31.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat31.setText("0");
        txtMinat31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat31FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat31FocusLost(evt);
            }
        });

        txtMinat32.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat32.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat32.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat32.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat32.setText("0");
        txtMinat32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat32FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat32FocusLost(evt);
            }
        });

        txtMinat33.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat33.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat33.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat33.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat33.setText("0");
        txtMinat33.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat33FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat33FocusLost(evt);
            }
        });

        txtMinat34.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat34.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat34.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat34.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat34.setText("0");
        txtMinat34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat34.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat34FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat34FocusLost(evt);
            }
        });

        txtMinat35.setBackground(new java.awt.Color(17, 157, 164));
        txtMinat35.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtMinat35.setForeground(new java.awt.Color(255, 255, 255));
        txtMinat35.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMinat35.setText("0");
        txtMinat35.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMinat35.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinat35FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMinat35FocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlInputNormalLayout = new javax.swing.GroupLayout(pnlInputNormal);
        pnlInputNormal.setLayout(pnlInputNormalLayout);
        pnlInputNormalLayout.setHorizontalGroup(
            pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputNormalLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputNormalLayout.createSequentialGroup()
                        .addComponent(txtMinat31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputNormalLayout.createSequentialGroup()
                        .addComponent(txtMinat21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputNormalLayout.createSequentialGroup()
                        .addComponent(txtMinat11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinat15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputNormalLayout.createSequentialGroup()
                        .addComponent(txtMTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMTK2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMTK4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMTK5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputNormalLayout.createSequentialGroup()
                        .addComponent(txtBing1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBing2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBing3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBing4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBing5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSemester, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInputNormalLayout.createSequentialGroup()
                            .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlInputNormalLayout.createSequentialGroup()
                                    .addComponent(lblSmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSmt3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSmt4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSmt5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInputNormalLayout.createSequentialGroup()
                                    .addComponent(txtBindo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBindo3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBindo4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBindo5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(54, 54, 54))
        );
        pnlInputNormalLayout.setVerticalGroup(
            pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputNormalLayout.createSequentialGroup()
                .addComponent(lblSemester)
                .addGap(4, 4, 4)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmt1)
                    .addComponent(lblSmt2)
                    .addComponent(lblSmt3)
                    .addComponent(lblSmt4)
                    .addComponent(lblSmt5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBindo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBindo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBindo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBindo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBindo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBing4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBing5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMTK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMTK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMTK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMTK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMTK5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinat11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinat21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinat31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinat35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pnlInputNilai.add(pnlInputNormal, "normal");

        pnlInputSimple.setBackground(new java.awt.Color(17, 157, 164));
        pnlInputSimple.setForeground(new java.awt.Color(255, 255, 255));

        txtInputRataBindo.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataBindo.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataBindo.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataBindo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataBindo.setText("0");
        txtInputRataBindo.setToolTipText("");
        txtInputRataBindo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataBindo.setPreferredSize(new java.awt.Dimension(35, 29));
        txtInputRataBindo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataBindoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataBindoFocusLost(evt);
            }
        });

        txtInputRataBing.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataBing.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataBing.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataBing.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataBing.setText("0");
        txtInputRataBing.setToolTipText("");
        txtInputRataBing.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataBing.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataBingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataBingFocusLost(evt);
            }
        });

        txtInputRataMTK.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataMTK.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataMTK.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataMTK.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataMTK.setText("0");
        txtInputRataMTK.setToolTipText("");
        txtInputRataMTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataMTK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataMTKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataMTKFocusLost(evt);
            }
        });

        txtInputRataMinat1.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataMinat1.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataMinat1.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataMinat1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataMinat1.setText("0");
        txtInputRataMinat1.setToolTipText("");
        txtInputRataMinat1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataMinat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataMinat1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataMinat1FocusLost(evt);
            }
        });

        txtInputRataMinat2.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataMinat2.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataMinat2.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataMinat2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataMinat2.setText("0");
        txtInputRataMinat2.setToolTipText("");
        txtInputRataMinat2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataMinat2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataMinat2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataMinat2FocusLost(evt);
            }
        });

        txtInputRataMinat3.setBackground(new java.awt.Color(17, 157, 164));
        txtInputRataMinat3.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputRataMinat3.setForeground(new java.awt.Color(255, 255, 255));
        txtInputRataMinat3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInputRataMinat3.setText("0");
        txtInputRataMinat3.setToolTipText("");
        txtInputRataMinat3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputRataMinat3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputRataMinat3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputRataMinat3FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RATA-RATA");

        javax.swing.GroupLayout pnlInputSimpleLayout = new javax.swing.GroupLayout(pnlInputSimple);
        pnlInputSimple.setLayout(pnlInputSimpleLayout);
        pnlInputSimpleLayout.setHorizontalGroup(
            pnlInputSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputSimpleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlInputSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtInputRataMinat3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtInputRataMinat2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtInputRataMinat1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtInputRataMTK, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtInputRataBing, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtInputRataBindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        pnlInputSimpleLayout.setVerticalGroup(
            pnlInputSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputSimpleLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInputRataBindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInputRataBing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInputRataMTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInputRataMinat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInputRataMinat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInputRataMinat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlInputNilai.add(pnlInputSimple, "simple");

        javax.swing.GroupLayout pnlJurusanLayout = new javax.swing.GroupLayout(pnlJurusan);
        pnlJurusan.setLayout(pnlJurusanLayout);
        pnlJurusanLayout.setHorizontalGroup(
            pnlJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJurusanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinat3)
                    .addComponent(lblMinat2)
                    .addComponent(lblMinat1)
                    .addComponent(lblMTK)
                    .addComponent(lblBIndo)
                    .addComponent(lblBIng))
                .addGap(18, 18, 18)
                .addComponent(pnlInputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlJurusanLayout.setVerticalGroup(
            pnlJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJurusanLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblBIndo)
                        .addGap(19, 19, 19)
                        .addComponent(lblBIng)
                        .addGap(19, 19, 19)
                        .addComponent(lblMTK)
                        .addGap(19, 19, 19)
                        .addComponent(lblMinat1)
                        .addGap(19, 19, 19)
                        .addComponent(lblMinat2)
                        .addGap(19, 19, 19)
                        .addComponent(lblMinat3))
                    .addComponent(pnlInputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFinish.setBackground(new java.awt.Color(25, 165, 174));
        btnFinish.setFont(new java.awt.Font("Gidolinya", 0, 24)); // NOI18N
        btnFinish.setForeground(new java.awt.Color(255, 255, 255));
        btnFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tick30x30.png"))); // NOI18N
        btnFinish.setText("SELESAI");
        btnFinish.setContentAreaFilled(false);
        btnFinish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinish.setIconTextGap(10);
        btnFinish.setOpaque(true);
        btnFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinishMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFinishMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFinishMouseReleased(evt);
            }
        });
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnUbahInput.setBackground(new java.awt.Color(25, 165, 174));
        btnUbahInput.setFont(new java.awt.Font("Gidole", 0, 18)); // NOI18N
        btnUbahInput.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bullets30x30.png"))); // NOI18N
        btnUbahInput.setText("MASUKKAN NILAI RATA-RATA SAJA");
        btnUbahInput.setContentAreaFilled(false);
        btnUbahInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahInput.setIconTextGap(10);
        btnUbahInput.setOpaque(true);
        btnUbahInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahInputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahInputMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUbahInputMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUbahInputMouseReleased(evt);
            }
        });
        btnUbahInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnUbahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNama)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(btnJurusanMIPA, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnJurusanIPS, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnJurusanIPS, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnJurusanMIPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahInput, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputRataBindoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataBindoFocusGained
        if("0".equals(txtInputRataBindo.getText())) {
            txtInputRataBindo.setText("");
        }
    }//GEN-LAST:event_txtInputRataBindoFocusGained

    private void txtInputRataBindoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataBindoFocusLost
        if(txtInputRataBindo.getText().isEmpty()) {
            txtInputRataBindo.setText("0");
        }
    }//GEN-LAST:event_txtInputRataBindoFocusLost

    private void txtInputRataBingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataBingFocusGained
        if("0".equals(txtInputRataBing.getText())) {
            txtInputRataBing.setText("");
        }
    }//GEN-LAST:event_txtInputRataBingFocusGained

    private void txtInputRataBingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataBingFocusLost
        if(txtInputRataBing.getText().isEmpty()) {
            txtInputRataBing.setText("0");
        }
    }//GEN-LAST:event_txtInputRataBingFocusLost

    private void txtInputRataMTKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMTKFocusGained
        if("0".equals(txtInputRataMTK.getText())) {
            txtInputRataMTK.setText("");
        }
    }//GEN-LAST:event_txtInputRataMTKFocusGained

    private void txtInputRataMTKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMTKFocusLost
        if(txtInputRataMTK.getText().isEmpty()) {
            txtInputRataMTK.setText("0");
        }
    }//GEN-LAST:event_txtInputRataMTKFocusLost

    private void txtInputRataMinat1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat1FocusGained
        if("0".equals(txtInputRataMinat1.getText())) {
            txtInputRataMinat1.setText("");
        }
    }//GEN-LAST:event_txtInputRataMinat1FocusGained

    private void txtInputRataMinat1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat1FocusLost
        if(txtInputRataMinat1.getText().isEmpty()) {
            txtInputRataMinat1.setText("0");
        }
    }//GEN-LAST:event_txtInputRataMinat1FocusLost

    private void txtInputRataMinat2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat2FocusGained
        if("0".equals(txtInputRataMinat2.getText())) {
            txtInputRataMinat2.setText("");
        }
    }//GEN-LAST:event_txtInputRataMinat2FocusGained

    private void txtInputRataMinat2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat2FocusLost
        if(txtInputRataMinat2.getText().isEmpty()) {
            txtInputRataMinat2.setText("0");
        }
    }//GEN-LAST:event_txtInputRataMinat2FocusLost

    private void txtInputRataMinat3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat3FocusGained
        if("0".equals(txtInputRataMinat3.getText())) {
            txtInputRataMinat3.setText("");
        }
    }//GEN-LAST:event_txtInputRataMinat3FocusGained

    private void txtInputRataMinat3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputRataMinat3FocusLost
        if(txtInputRataMinat3.getText().isEmpty()) {
            txtInputRataMinat3.setText("0");
        }
    }//GEN-LAST:event_txtInputRataMinat3FocusLost

    private void btnJurusanMIPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurusanMIPAActionPerformed
        ips = false;
        lblMinat1.setText("Fisika");
        lblMinat2.setText("Kimia");
        lblMinat3.setText("Biologi");
        btnJurusanIPS.setBorder(Data.OptionUnselected());
    }//GEN-LAST:event_btnJurusanMIPAActionPerformed

    private void btnJurusanMIPAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMIPAMouseEntered
        btnJurusanMIPA.setBorder(Data.OptionSelected());
    }//GEN-LAST:event_btnJurusanMIPAMouseEntered

    private void btnJurusanMIPAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMIPAMouseExited
        if(ips) {
            btnJurusanMIPA.setBorder(Data.OptionUnselected());
        }
        else btnJurusanMIPA.setBorder(Data.OptionSelected());
    }//GEN-LAST:event_btnJurusanMIPAMouseExited

    private void btnJurusanMIPAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMIPAMousePressed
        btnJurusanMIPA.setBackground(new Color(25, 180, 180));
    }//GEN-LAST:event_btnJurusanMIPAMousePressed

    private void btnJurusanMIPAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMIPAMouseReleased
        btnJurusanMIPA.setBackground(new Color(17, 157, 164));
    }//GEN-LAST:event_btnJurusanMIPAMouseReleased

    private void btnJurusanIPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurusanIPSActionPerformed
        ips = true;
        lblMinat1.setText("Sosiologi");
        lblMinat2.setText("Geografi");
        lblMinat3.setText("Ekonomi");
        btnJurusanMIPA.setBorder(Data.OptionUnselected());
    }//GEN-LAST:event_btnJurusanIPSActionPerformed

    private void btnJurusanIPSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanIPSMouseEntered
        btnJurusanIPS.setBorder(Data.OptionSelected());
    }//GEN-LAST:event_btnJurusanIPSMouseEntered

    private void btnJurusanIPSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanIPSMouseExited
        if (ips) {
            btnJurusanIPS.setBorder(Data.OptionSelected());
        }
        else btnJurusanIPS.setBorder(Data.OptionUnselected());
    }//GEN-LAST:event_btnJurusanIPSMouseExited

    private void btnJurusanIPSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanIPSMousePressed
        btnJurusanIPS.setBackground(new Color(25, 180, 180));
    }//GEN-LAST:event_btnJurusanIPSMousePressed

    private void btnJurusanIPSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanIPSMouseReleased
        btnJurusanIPS.setBackground(new Color(17, 157, 164));
    }//GEN-LAST:event_btnJurusanIPSMouseReleased

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        Main dashboard = new Main();
        int[] n1 = {Integer.parseInt(txtBindo1.getText()), Integer.parseInt(txtBindo2.getText()), Integer.parseInt(txtBindo3.getText()), Integer.parseInt(txtBindo4.getText()), Integer.parseInt(txtBindo5.getText())};
        int[] n2 = {Integer.parseInt(txtBing1.getText()), Integer.parseInt(txtBing2.getText()), Integer.parseInt(txtBing3.getText()), Integer.parseInt(txtBing4.getText()), Integer.parseInt(txtBing5.getText())};
        int[] n3 = {Integer.parseInt(txtMTK1.getText()), Integer.parseInt(txtMTK2.getText()), Integer.parseInt(txtMTK3.getText()), Integer.parseInt(txtMTK4.getText()), Integer.parseInt(txtMTK5.getText())};
        int[] n4 = {Integer.parseInt(txtMinat11.getText()), Integer.parseInt(txtMinat12.getText()), Integer.parseInt(txtMinat13.getText()), Integer.parseInt(txtMinat14.getText()), Integer.parseInt(txtMinat15.getText())};
        int[] n5 = {Integer.parseInt(txtMinat21.getText()), Integer.parseInt(txtMinat22.getText()), Integer.parseInt(txtMinat23.getText()), Integer.parseInt(txtMinat24.getText()), Integer.parseInt(txtMinat25.getText())};
        int[] n6 = {Integer.parseInt(txtMinat31.getText()), Integer.parseInt(txtMinat32.getText()), Integer.parseInt(txtMinat33.getText()), Integer.parseInt(txtMinat34.getText()), Integer.parseInt(txtMinat35.getText())};
        float[] rata = {Float.parseFloat(txtInputRataBindo.getText()), Float.parseFloat(txtInputRataBing.getText()), Float.parseFloat(txtInputRataMTK.getText()), Float.parseFloat(txtInputRataMinat1.getText()), Float.parseFloat(txtInputRataMinat2.getText()), Float.parseFloat(txtInputRataMinat3.getText())};
        if (btnUbahInput.isSelected()) {
            Data.InputRaporSimple(ips, rata);
        }
        else {
            Data.InputRaporNormal(ips, n1, n2, n3, n4, n5, n6);
        }
        Main.lblNama.setText("Selamat datang, " + Data.nama);
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnFinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseEntered
        btnFinish.setBackground(new Color(30, 180, 190));
    }//GEN-LAST:event_btnFinishMouseEntered

    private void btnFinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseExited
        btnFinish.setBackground(new Color(25, 165, 174));
    }//GEN-LAST:event_btnFinishMouseExited

    private void btnFinishMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMousePressed
        btnFinish.setBackground(new Color(37, 170, 180));
    }//GEN-LAST:event_btnFinishMousePressed

    private void btnFinishMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseReleased
        btnFinish.setBackground(new Color(30, 180, 190));
    }//GEN-LAST:event_btnFinishMouseReleased

    private void txtBindo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo1FocusGained
        if("0".equals(txtBindo1.getText())) {
            txtBindo1.setText("");
        }
    }//GEN-LAST:event_txtBindo1FocusGained

    private void txtBindo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo1FocusLost
        if(txtBindo1.getText().isEmpty()) {
            txtBindo1.setText("0");
        }
    }//GEN-LAST:event_txtBindo1FocusLost

    private void txtBindo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo2FocusGained
        if("0".equals(txtBindo2.getText())) {
            txtBindo2.setText("");
        }
    }//GEN-LAST:event_txtBindo2FocusGained

    private void txtBindo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo2FocusLost
        if(txtBindo2.getText().isEmpty()) {
            txtBindo2.setText("0");
        }
    }//GEN-LAST:event_txtBindo2FocusLost

    private void txtBindo3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo3FocusGained
        if("0".equals(txtBindo3.getText())) {
            txtBindo3.setText("");
        }
    }//GEN-LAST:event_txtBindo3FocusGained

    private void txtBindo3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo3FocusLost
        if(txtBindo3.getText().isEmpty()) {
            txtBindo3.setText("0");
        }
    }//GEN-LAST:event_txtBindo3FocusLost

    private void txtBindo4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo4FocusGained
        if("0".equals(txtBindo4.getText())) {
            txtBindo4.setText("");
        }
    }//GEN-LAST:event_txtBindo4FocusGained

    private void txtBindo4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo4FocusLost
        if(txtBindo4.getText().isEmpty()) {
            txtBindo4.setText("0");
        }
    }//GEN-LAST:event_txtBindo4FocusLost

    private void txtBindo5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo5FocusGained
        if("0".equals(txtBindo5.getText())) {
            txtBindo5.setText("");
        }
    }//GEN-LAST:event_txtBindo5FocusGained

    private void txtBindo5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindo5FocusLost
        if(txtBindo5.getText().isEmpty()) {
            txtBindo5.setText("0");
        }
    }//GEN-LAST:event_txtBindo5FocusLost

    private void txtBing1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing1FocusGained
        if("0".equals(txtBing1.getText())) {
            txtBing1.setText("");
        }
    }//GEN-LAST:event_txtBing1FocusGained

    private void txtBing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing1FocusLost
        if(txtBing1.getText().isEmpty()) {
            txtBing1.setText("0");
        }
    }//GEN-LAST:event_txtBing1FocusLost

    private void txtBing2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing2FocusGained
        if("0".equals(txtBing2.getText())) {
            txtBing2.setText("");
        }
    }//GEN-LAST:event_txtBing2FocusGained

    private void txtBing2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing2FocusLost
        if(txtBing2.getText().isEmpty()) {
            txtBing2.setText("0");
        }
    }//GEN-LAST:event_txtBing2FocusLost

    private void txtBing3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing3FocusGained
        if("0".equals(txtBing3.getText())) {
            txtBing3.setText("");
        }
    }//GEN-LAST:event_txtBing3FocusGained

    private void txtBing3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing3FocusLost
        if(txtBing3.getText().isEmpty()) {
            txtBing3.setText("0");
        }
    }//GEN-LAST:event_txtBing3FocusLost

    private void txtBing4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing4FocusGained
        if("0".equals(txtBing4.getText())) {
            txtBing4.setText("");
        }
    }//GEN-LAST:event_txtBing4FocusGained

    private void txtBing4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing4FocusLost
        if(txtBing4.getText().isEmpty()) {
            txtBing4.setText("0");
        }
    }//GEN-LAST:event_txtBing4FocusLost

    private void txtBing5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing5FocusGained
        if("0".equals(txtBing5.getText())) {
            txtBing5.setText("");
        }
    }//GEN-LAST:event_txtBing5FocusGained

    private void txtBing5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBing5FocusLost
        if(txtBing5.getText().isEmpty()) {
            txtBing5.setText("0");
        }
    }//GEN-LAST:event_txtBing5FocusLost

    private void txtMTK1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK1FocusGained
        if("0".equals(txtMTK1.getText())) {
            txtMTK1.setText("");
        }
    }//GEN-LAST:event_txtMTK1FocusGained

    private void txtMTK1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK1FocusLost
        if(txtMTK1.getText().isEmpty()) {
            txtMTK1.setText("0");
        }
    }//GEN-LAST:event_txtMTK1FocusLost

    private void txtMTK2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK2FocusGained
        if("0".equals(txtMTK2.getText())) {
            txtMTK2.setText("");
        }
    }//GEN-LAST:event_txtMTK2FocusGained

    private void txtMTK2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK2FocusLost
        if(txtMTK2.getText().isEmpty()) {
            txtMTK2.setText("0");
        }
    }//GEN-LAST:event_txtMTK2FocusLost

    private void txtMTK3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK3FocusGained
        if("0".equals(txtMTK3.getText())) {
            txtMTK3.setText("");
        }
    }//GEN-LAST:event_txtMTK3FocusGained

    private void txtMTK3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK3FocusLost
        if(txtMTK3.getText().isEmpty()) {
            txtMTK3.setText("0");
        }
    }//GEN-LAST:event_txtMTK3FocusLost

    private void txtMTK4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK4FocusGained
        if("0".equals(txtMTK4.getText())) {
            txtMTK4.setText("");
        }
    }//GEN-LAST:event_txtMTK4FocusGained

    private void txtMTK4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK4FocusLost
        if(txtMTK4.getText().isEmpty()) {
            txtMTK4.setText("0");
        }
    }//GEN-LAST:event_txtMTK4FocusLost

    private void txtMTK5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK5FocusGained
        if("0".equals(txtMTK5.getText())) {
            txtMTK5.setText("");
        }
    }//GEN-LAST:event_txtMTK5FocusGained

    private void txtMTK5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMTK5FocusLost
        if(txtMTK5.getText().isEmpty()) {
            txtMTK5.setText("0");
        }
    }//GEN-LAST:event_txtMTK5FocusLost

    private void txtMinat11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat11FocusGained
        if("0".equals(txtMinat11.getText())) {
            txtMinat11.setText("");
        }
    }//GEN-LAST:event_txtMinat11FocusGained

    private void txtMinat11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat11FocusLost
        if(txtMinat11.getText().isEmpty()) {
            txtMinat11.setText("0");
        }
    }//GEN-LAST:event_txtMinat11FocusLost

    private void txtMinat12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat12FocusGained
        if("0".equals(txtMinat12.getText())) {
            txtMinat12.setText("");
        }
    }//GEN-LAST:event_txtMinat12FocusGained

    private void txtMinat12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat12FocusLost
        if(txtMinat12.getText().isEmpty()) {
            txtMinat12.setText("0");
        }
    }//GEN-LAST:event_txtMinat12FocusLost

    private void txtMinat13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat13FocusGained
        if("0".equals(txtMinat13.getText())) {
            txtMinat13.setText("");
        }
    }//GEN-LAST:event_txtMinat13FocusGained

    private void txtMinat13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat13FocusLost
        if(txtMinat13.getText().isEmpty()) {
            txtMinat13.setText("0");
        }
    }//GEN-LAST:event_txtMinat13FocusLost

    private void txtMinat14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat14FocusGained
        if("0".equals(txtMinat14.getText())) {
            txtMinat14.setText("");
        }
    }//GEN-LAST:event_txtMinat14FocusGained

    private void txtMinat14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat14FocusLost
        if(txtMinat14.getText().isEmpty()) {
            txtMinat14.setText("0");
        }
    }//GEN-LAST:event_txtMinat14FocusLost

    private void txtMinat15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat15FocusGained
        if("0".equals(txtMinat15.getText())) {
            txtMinat15.setText("");
        }
    }//GEN-LAST:event_txtMinat15FocusGained

    private void txtMinat15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat15FocusLost
        if(txtMinat15.getText().isEmpty()) {
            txtMinat15.setText("0");
        }
    }//GEN-LAST:event_txtMinat15FocusLost

    private void txtMinat21FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat21FocusGained
        if("0".equals(txtMinat21.getText())) {
            txtMinat21.setText("");
        }
    }//GEN-LAST:event_txtMinat21FocusGained

    private void txtMinat21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat21FocusLost
        if(txtMinat21.getText().isEmpty()) {
            txtMinat21.setText("0");
        }
    }//GEN-LAST:event_txtMinat21FocusLost

    private void txtMinat22FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat22FocusGained
        if("0".equals(txtMinat22.getText())) {
            txtMinat22.setText("");
        }
    }//GEN-LAST:event_txtMinat22FocusGained

    private void txtMinat22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat22FocusLost
        if(txtMinat22.getText().isEmpty()) {
            txtMinat22.setText("0");
        }
    }//GEN-LAST:event_txtMinat22FocusLost

    private void txtMinat23FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat23FocusGained
        if("0".equals(txtMinat23.getText())) {
            txtMinat23.setText("");
        }
    }//GEN-LAST:event_txtMinat23FocusGained

    private void txtMinat23FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat23FocusLost
        if(txtMinat23.getText().isEmpty()) {
            txtMinat23.setText("0");
        }
    }//GEN-LAST:event_txtMinat23FocusLost

    private void txtMinat24FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat24FocusGained
        if("0".equals(txtMinat24.getText())) {
            txtMinat24.setText("");
        }
    }//GEN-LAST:event_txtMinat24FocusGained

    private void txtMinat24FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat24FocusLost
        if(txtMinat24.getText().isEmpty()) {
            txtMinat24.setText("0");
        }
    }//GEN-LAST:event_txtMinat24FocusLost

    private void txtMinat25FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat25FocusGained
        if("0".equals(txtMinat25.getText())) {
            txtMinat25.setText("");
        }
    }//GEN-LAST:event_txtMinat25FocusGained

    private void txtMinat25FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat25FocusLost
        if(txtMinat25.getText().isEmpty()) {
            txtMinat25.setText("0");
        }
    }//GEN-LAST:event_txtMinat25FocusLost

    private void txtMinat31FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat31FocusGained
        if("0".equals(txtMinat31.getText())) {
            txtMinat31.setText("");
        }
    }//GEN-LAST:event_txtMinat31FocusGained

    private void txtMinat31FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat31FocusLost
        if(txtMinat31.getText().isEmpty()) {
            txtMinat31.setText("0");
        }
    }//GEN-LAST:event_txtMinat31FocusLost

    private void txtMinat32FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat32FocusGained
        if("0".equals(txtMinat32.getText())) {
            txtMinat32.setText("");
        }
    }//GEN-LAST:event_txtMinat32FocusGained

    private void txtMinat32FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat32FocusLost
        if(txtMinat32.getText().isEmpty()) {
            txtMinat32.setText("0");
        }
    }//GEN-LAST:event_txtMinat32FocusLost

    private void txtMinat33FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat33FocusGained
        if("0".equals(txtMinat33.getText())) {
            txtMinat33.setText("");
        }
    }//GEN-LAST:event_txtMinat33FocusGained

    private void txtMinat33FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat33FocusLost
        if(txtMinat33.getText().isEmpty()) {
            txtMinat33.setText("0");
        }
    }//GEN-LAST:event_txtMinat33FocusLost

    private void txtMinat34FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat34FocusGained
        if("0".equals(txtMinat34.getText())) {
            txtMinat34.setText("");
        }
    }//GEN-LAST:event_txtMinat34FocusGained

    private void txtMinat34FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat34FocusLost
        if(txtMinat34.getText().isEmpty()) {
            txtMinat34.setText("0");
        }
    }//GEN-LAST:event_txtMinat34FocusLost

    private void txtMinat35FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat35FocusGained
        if("0".equals(txtMinat35.getText())) {
            txtMinat35.setText("");
        }
    }//GEN-LAST:event_txtMinat35FocusGained

    private void txtMinat35FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinat35FocusLost
        if(txtMinat35.getText().isEmpty()) {
            txtMinat35.setText("0");
        }
    }//GEN-LAST:event_txtMinat35FocusLost

    private void btnUbahInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahInputActionPerformed
        CardLayout menu = (CardLayout) pnlInputNilai.getLayout();
        if(btnUbahInput.isSelected()) {
            menu.show(pnlInputNilai, "simple");
            btnUbahInput.setText("MASUKKAN NILAI PER SEMESTER");
            btnUbahInput.setIcon(complex);
        }
        else {
            menu.show(pnlInputNilai, "normal");
            btnUbahInput.setText("MASUKKAN NILAI RATA-RATA SAJA");
            btnUbahInput.setIcon(simple);
        }
    }//GEN-LAST:event_btnUbahInputActionPerformed

    private void btnUbahInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahInputMouseEntered
        btnUbahInput.setBackground(new Color(30, 180, 190));
    }//GEN-LAST:event_btnUbahInputMouseEntered

    private void btnUbahInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahInputMouseExited
        btnUbahInput.setBackground(new Color(25, 165, 174));
    }//GEN-LAST:event_btnUbahInputMouseExited

    private void btnUbahInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahInputMousePressed
        btnUbahInput.setBackground(new Color(37, 170, 180));
    }//GEN-LAST:event_btnUbahInputMousePressed

    private void btnUbahInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahInputMouseReleased
        btnUbahInput.setBackground(new Color(30, 180, 190));
    }//GEN-LAST:event_btnUbahInputMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnFinish;
    private javax.swing.JButton btnJurusanIPS;
    private javax.swing.JButton btnJurusanMIPA;
    private javax.swing.JToggleButton btnUbahInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBIndo;
    private javax.swing.JLabel lblBIng;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblMTK;
    private javax.swing.JLabel lblMenuName;
    private javax.swing.JLabel lblMinat1;
    private javax.swing.JLabel lblMinat2;
    private javax.swing.JLabel lblMinat3;
    public static javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSmt1;
    private javax.swing.JLabel lblSmt2;
    private javax.swing.JLabel lblSmt3;
    private javax.swing.JLabel lblSmt4;
    private javax.swing.JLabel lblSmt5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlInputNilai;
    private javax.swing.JPanel pnlInputNormal;
    private javax.swing.JPanel pnlInputSimple;
    private javax.swing.JPanel pnlJurusan;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtBindo1;
    private javax.swing.JTextField txtBindo2;
    private javax.swing.JTextField txtBindo3;
    private javax.swing.JTextField txtBindo4;
    private javax.swing.JTextField txtBindo5;
    private javax.swing.JTextField txtBing1;
    private javax.swing.JTextField txtBing2;
    private javax.swing.JTextField txtBing3;
    private javax.swing.JTextField txtBing4;
    private javax.swing.JTextField txtBing5;
    private javax.swing.JTextField txtInputRataBindo;
    private javax.swing.JTextField txtInputRataBing;
    private javax.swing.JTextField txtInputRataMTK;
    private javax.swing.JTextField txtInputRataMinat1;
    private javax.swing.JTextField txtInputRataMinat2;
    private javax.swing.JTextField txtInputRataMinat3;
    private javax.swing.JTextField txtMTK1;
    private javax.swing.JTextField txtMTK2;
    private javax.swing.JTextField txtMTK3;
    private javax.swing.JTextField txtMTK4;
    private javax.swing.JTextField txtMTK5;
    private javax.swing.JTextField txtMinat11;
    private javax.swing.JTextField txtMinat12;
    private javax.swing.JTextField txtMinat13;
    private javax.swing.JTextField txtMinat14;
    private javax.swing.JTextField txtMinat15;
    private javax.swing.JTextField txtMinat21;
    private javax.swing.JTextField txtMinat22;
    private javax.swing.JTextField txtMinat23;
    private javax.swing.JTextField txtMinat24;
    private javax.swing.JTextField txtMinat25;
    private javax.swing.JTextField txtMinat31;
    private javax.swing.JTextField txtMinat32;
    private javax.swing.JTextField txtMinat33;
    private javax.swing.JTextField txtMinat34;
    private javax.swing.JTextField txtMinat35;
    // End of variables declaration//GEN-END:variables
}
