/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author Edho
 */
public class Splash extends javax.swing.JFrame {
    
    public ImageIcon cross = new javax.swing.ImageIcon(getClass().getResource("/Icons/cross30x30.png"));
    public ImageIcon next = new javax.swing.ImageIcon(getClass().getResource("/Icons/next30x30.png"));
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        pnlLogo = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        lblSelamatDatang = new javax.swing.JLabel();
        txtInputNama = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlLogo.setBackground(new java.awt.Color(12, 142, 148));

        lblLogo1.setFont(new java.awt.Font("GOGOIA", 0, 64)); // NOI18N
        lblLogo1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo1.setText("Predictator");

        lblLogo2.setFont(new java.awt.Font("Akrobat SemiBold", 0, 24)); // NOI18N
        lblLogo2.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo2.setText("BETTER THAN RIPAAJP");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBody.setBackground(new java.awt.Color(17, 157, 164));

        lblSelamatDatang.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        lblSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        lblSelamatDatang.setText("Selamat datang,");

        txtInputNama.setBackground(new java.awt.Color(17, 157, 164));
        txtInputNama.setFont(new java.awt.Font("Gidole", 0, 24)); // NOI18N
        txtInputNama.setForeground(new java.awt.Color(230, 230, 230));
        txtInputNama.setText("Masukkan nama...");
        txtInputNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtInputNama.setOpaque(false);
        txtInputNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputNamaFocusGained(evt);
            }
        });
        txtInputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputNamaActionPerformed(evt);
            }
        });
        txtInputNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputNamaKeyTyped(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(36, 138, 145));
        btnNext.setFont(new java.awt.Font("Gidolinya", 0, 36)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross30x30.png"))); // NOI18N
        btnNext.setText("ISI NAMA");
        btnNext.setBorder(null);
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setEnabled(false);
        btnNext.setIconTextGap(10);
        btnNext.setOpaque(true);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNextMouseReleased(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBodyLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelamatDatang)
                            .addComponent(txtInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblSelamatDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputNamaFocusGained
        if("Masukkan nama...".equals(txtInputNama.getText())) {
            txtInputNama.setText("");
            txtInputNama.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtInputNamaFocusGained

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        Data.nama = txtInputNama.getText();
        InputNilai next = new InputNilai();
        next.setVisible(true);
        InputNilai.lblNama.setText("Halo, " + Data.nama + "!");
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        if(btnNext.isEnabled()) {
            btnNext.setBackground(new Color(30, 180, 190));
        }
        else {
            Border selected = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE);
            txtInputNama.setBorder(selected);
        }
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        if(btnNext.isEnabled()) {
            btnNext.setBackground(new Color(25, 165, 174));
        }
        else {
            Border selected = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE);
            txtInputNama.setBorder(selected);
        }
    }//GEN-LAST:event_btnNextMouseExited

    private void btnNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMousePressed
        if(btnNext.isEnabled()) {
            btnNext.setBackground(new Color(37, 170, 180));
        }
    }//GEN-LAST:event_btnNextMousePressed

    private void btnNextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseReleased
        if(btnNext.isEnabled()) {
            btnNext.setBackground(new Color(30, 180, 190));
        }
    }//GEN-LAST:event_btnNextMouseReleased

    private void txtInputNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputNamaKeyTyped
        if(txtInputNama.getText().isEmpty()) {
            btnNext.setEnabled(false);
            btnNext.setText("ISI NAMA");
            btnNext.setBackground(new Color(36, 138, 145));
            btnNext.setIcon(cross);
            btnNext.setHorizontalTextPosition(SwingConstants.TRAILING);
        }
        else {
            btnNext.setEnabled(true);
            btnNext.setText("LANJUT");
            btnNext.setBackground(new Color(25, 165, 174));
            btnNext.setIcon(next);
            btnNext.setHorizontalTextPosition(SwingConstants.LEADING);
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                Data.nama = txtInputNama.getText();
                InputNilai next = new InputNilai();
                next.setVisible(true);
                InputNilai.lblNama.setText("Halo, " + Data.nama + "!");
                dispose();
        }
        }
    }//GEN-LAST:event_txtInputNamaKeyTyped

    private void txtInputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblSelamatDatang;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JTextField txtInputNama;
    // End of variables declaration//GEN-END:variables
}
